### PR TITLE
p2pool-node-status returns 404 error

### PR DESCRIPTION
**Pull request by buzzkillb**

### CODE REVIEW

**Comment by charlesrocket** [comment]
what about https://github.com/aatje92/p2pool-node-status ?

**Comment by Altcoin-Cash** [comment]
> 
> 
> what about https://github.com/aatje92/p2pool-node-status ?

That's a fork of the missing, but lack some commits 
https://web.archive.org/web/20180611021505/https://github.com/johndoe75/p2pool-node-status

**Comment by charlesrocket** [comment]
thats pretty much my point - maybe better test that fork instead of backspacing/injecting

**Comment by charlesrocket** [comment]
Merged to master 60a80b6c4ade1242f36e5855d77cd71ef27ec09e

**Pull request closed without merging**
